const GRAVE={id:'grave-asphodel',name:'Grave Asphodel',desc:'Solemn and elegant, it embodies death’s ineluctability.',effects:[{title:'ONE VISIBLE ENEMY → SHAKEN',text:'At the end of your turn, you may choose an enemy you can see. If you do, that enemy suffers Shaken.'},{title:'ALL VISIBLE ENEMIES → SHAKEN',text:'At the end of your turn, every enemy you can see suffers Shaken.'},{title:'SHAKEN ENEMIES → DARK DAMAGE',text:'At the end of your turn, deal [15 + your Skill Level in Chloromancy] dark damage to each enemy you can see who is suffering from Shaken.'}]};
const $=id=>document.getElementById(id);let seeds=[],activeId=null,preparedId='grave-asphodel',growth=0,level=1,maturing=false,dragging=false,pointerId=null;
function load(){try{const s=JSON.parse(localStorage.getItem('floralistV4')||'null');seeds=s?.seeds?.length?s.seeds:[GRAVE];if(!seeds.some(x=>x.id==='grave-asphodel'))seeds.unshift(GRAVE);activeId=s?.activeId||null;preparedId=s?.preparedId||'grave-asphodel';growth=Math.max(0,Math.min(3,Number(s?.growth)||0));level=Math.max(1,Math.min(99,Number(s?.level)||1));}catch(e){seeds=[GRAVE]}}
function save(){localStorage.setItem('floralistV4',JSON.stringify({seeds,activeId,preparedId,growth,level}))}
function active(){return seeds.find(s=>s.id===activeId)||null}function prepared(){return seeds.find(s=>s.id===preparedId)||seeds[0]}
function bonus(){return level>=50?10:level>=30?5:0}
function effectText(seed,i){let t=seed.effects[i]?.text||'No effect entered.';if(i===2&&bonus())t+=' Level bonus: +'+bonus()+' damage.';return t}
function renderList(){$('seedList').innerHTML=seeds.map(s=>`<div class="seed-card"><div><strong>${s.name}</strong><small>${s.desc}</small></div><button class="btn mini" data-prep="${s.id}">${s.id===preparedId?'Prepared':'Prepare'}</button></div>`).join('');document.querySelectorAll('[data-prep]').forEach(b=>b.addEventListener('click',()=>{if(activeId)return;preparedId=b.dataset.prep;render()}))}
function setEffects(s){s=s||GRAVE;for(let i=0;i<3;i++){$('e'+(i+1)+'title').textContent=s.effects[i]?.title||('Effect '+(i+1));$('e'+(i+1)+'text').textContent=effectText(s,i)}}
function render(){const a=active(),p=prepared();$('scene').className='scene g'+growth;for(let i=1;i<=4;i++)$('seg'+i).classList.toggle('done',!!a&&i<=growth);$('clockText').textContent=(a?growth:0)+' / 4';$('charLevel').value=level;if(a){$('seedName').textContent=a.name;$('seedDesc').textContent=a.desc;$('statusLine').textContent=growth===0?'Planted · Growth Clock Empty':`Growth ${growth}/4 · Effect ${growth} Active`;$('seedToken').classList.add('hidden');$('dragLabel').classList.add('hidden');$('endTurn').disabled=false;$('newScene').disabled=false;$('removeSeed').disabled=false;setEffects(a)}else{$('seedName').textContent='No Magiseed Planted';$('seedDesc').textContent='Prepare a seed from your bag, then drag it into the small hole in the skull.';$('statusLine').textContent='Garden Empty';$('seedToken').classList.toggle('hidden',!p);$('dragLabel').classList.toggle('hidden',!p);$('endTurn').disabled=true;$('newScene').disabled=true;$('removeSeed').disabled=true;setEffects(p)}for(let i=1;i<=3;i++)$('effect'+i).classList.toggle('active',!!a&&growth===i);$('mature').classList.remove('active');renderList();save()}
function wisps(n){const f=$('wisps');for(let i=0;i<n;i++){const w=document.createElement('i');w.className='wisp';w.style.left=(40+Math.random()*20)+'%';w.style.top=(48+Math.random()*18)+'%';w.style.setProperty('--dx',(Math.random()*180-90)+'px');w.style.setProperty('--dy',(-70-Math.random()*120)+'px');w.style.animationDelay=(i*.03)+'s';f.appendChild(w);setTimeout(()=>w.remove(),1800)}}
function plant(){if(activeId||!prepared())return;activeId=preparedId;growth=0;wisps(12);render()}
function mature(){if(maturing)return;maturing=true;growth=4;$('scene').className='scene g4';for(let i=1;i<=4;i++)$('seg'+i).classList.add('done');for(let i=1;i<=3;i++)$('effect'+i).classList.remove('active');$('mature').classList.add('active');$('clockText').textContent='4 / 4';$('notice').classList.add('show');wisps(26);setTimeout(()=>{$('notice').classList.remove('show');activeId=null;growth=0;maturing=false;render()},1900)}
$('endTurn').onclick=()=>{if(!active()||maturing)return;if(growth<3){growth++;wisps(8+growth*3);render()}else mature()};$('newScene').onclick=()=>{if(active()&&!maturing){growth=0;wisps(5);render()}};$('removeSeed').onclick=()=>{if(active()&&!maturing){activeId=null;growth=0;wisps(6);render()}};$('applyLevel').onclick=()=>{level=Math.max(1,Math.min(99,Number($('charLevel').value)||1));render()};
$('openBag').onclick=()=>$('bagModal').classList.add('open');$('closeBag').onclick=()=>$('bagModal').classList.remove('open');$('bagModal').addEventListener('click',e=>{if(e.target===$('bagModal'))$('bagModal').classList.remove('open')});
$('saveSeed').onclick=()=>{const name=$('newName').value.trim();if(!name){alert('Give the Magiseed a name first.');return}const id=name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||('seed-'+Date.now());const seed={id,name,desc:$('newDesc').value.trim()||'A custom Magiseed.',effects:[{title:$('newE1Title').value.trim()||'Effect I',text:$('newE1').value.trim()||'No effect entered.'},{title:$('newE2Title').value.trim()||'Effect II',text:$('newE2').value.trim()||'No effect entered.'},{title:$('newE3Title').value.trim()||'Effect III',text:$('newE3').value.trim()||'No effect entered.'}]};const ix=seeds.findIndex(s=>s.id===id);if(ix>=0)seeds[ix]=seed;else seeds.push(seed);preparedId=id;['newName','newDesc','newE1Title','newE1','newE2Title','newE2','newE3Title','newE3'].forEach(x=>$(x).value='');$('bagModal').classList.remove('open');render()};
function moveSeed(x,y){const t=$('seedToken'),d=$('skullDrop').getBoundingClientRect();t.style.position='fixed';t.style.left=x+'px';t.style.top=y+'px';t.style.bottom='auto';t.style.transform='translate(-50%,-50%) rotate(-12deg)';t.classList.add('held');const inside=x>d.left&&x<d.right&&y>d.top&&y<d.bottom;$('skullDrop').classList.toggle('hot',inside);return inside}
$('seedToken').addEventListener('pointerdown',e=>{if(activeId)return;dragging=true;pointerId=e.pointerId;$('seedToken').setPointerCapture(pointerId);moveSeed(e.clientX,e.clientY)});$('seedToken').addEventListener('pointermove',e=>{if(dragging)moveSeed(e.clientX,e.clientY)});$('seedToken').addEventListener('pointerup',e=>{if(!dragging)return;const inside=moveSeed(e.clientX,e.clientY);dragging=false;$('seedToken').releasePointerCapture(pointerId);const t=$('seedToken');t.style.position='absolute';t.style.left='18%';t.style.top='auto';t.style.bottom='28px';t.style.transform='rotate(-12deg)';t.classList.remove('held');$('skullDrop').classList.remove('hot');if(inside)plant()});$('seedToken').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();plant()}});$('skullDrop').onclick=()=>{if(!activeId&&prepared())plant()};
load();render();